apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
spec:
  group: velero.io
  names:
    kind: BackupStorageLocation
    plural: backupstoragelocations
    singular: backupstoragelocation
    listKind: BackupStorageLocationList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

