apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
spec:
  group: velero.io
  names:
    kind: Backup
    plural: backups
    singular: backup
    listKind: BackupList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

