apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deletebackuprequests.velero.io
spec:
  group: velero.io
  names:
    kind: DeleteBackupRequest
    plural: deletebackuprequests
    singular: deletebackuprequest
    listKind: DeleteBackupRequestList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

