apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: downloadrequests.velero.io
spec:
  group: velero.io
  names:
    kind: DownloadRequest
    plural: downloadrequests
    singular: downloadrequest
    listKind: DownloadRequestList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

