apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumerestores.velero.io
spec:
  group: velero.io
  names:
    kind: PodVolumeRestore
    plural: podvolumerestores
    singular: podvolumerestore
    listKind: PodVolumeRestoreList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

