apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podvolumebackups.velero.io
spec:
  group: velero.io
  names:
    kind: PodVolumeBackup
    plural: podvolumebackups
    singular: podvolumebackup
    listKind: PodVolumeBackupList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

