apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
spec:
  group: velero.io
  names:
    kind: Restore
    plural: restores
    singular: restore
    listKind: RestoreList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

