apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resticrepositories.velero.io
spec:
  group: velero.io
  names:
    kind: ResticRepository
    plural: resticrepositories
    singular: resticrepository
    listKind: ResticRepositoryList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

