apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
spec:
  group: velero.io
  names:
    kind: Schedule
    plural: schedules
    singular: schedule
    listKind: ScheduleList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

