apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serverstatusrequests.velero.io
spec:
  group: velero.io
  names:
    kind: ServerStatusRequest
    plural: serverstatusrequests
    singular: serverstatusrequest
    listKind: ServerStatusRequestList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

