apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
spec:
  group: velero.io
  names:
    kind: VolumeSnapshotLocation
    plural: volumesnapshotlocations
    singular: volumesnapshotlocation
    listKind: VolumeSnapshotLocationList
  scope: Namespaced
  version: v1
  preserveUnknownFields: true

